// Generates supabase/migrations/0002_seed.sql from the sample fixture, so the
// 11 starter recipes have exactly one definition: the one the domain tests
// already assert against.
//
//   npm run seed:sql
//
// The SQL matches rows by name rather than baking in generated ids, so it is
// idempotent and readable.

import { createServer } from "vite";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const server = await createServer({
  root,
  configFile: false,
  server: { middlewareMode: true },
  appType: "custom",
  logLevel: "warn",
});
const fx = await server.ssrLoadModule("./lib/domain/fixtures/sample.ts");
await server.close();

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (xs) => (xs.length ? `array[${xs.map(q).join(", ")}]` : "'{}'::text[]");

const lines = [];
const w = (s = "") => lines.push(s);

w(`-- Starter data: the ${fx.sampleRecipes.length} recipes from the prototype, their`);
w("-- ingredients, and the two pantry lists. Generated by scripts/make-seed.mjs;");
w("-- edit the fixture at lib/domain/fixtures/sample.ts and regenerate rather");
w("-- than editing this file. Safe to re-run: it inserts only what is missing.");
w();
w("-- Ingredients, including which pantry list each one is on.");
w("insert into app_mealprep.ingredients (household_id, name, default_aisle, pantry_status)");
w("select h.id, v.name, v.aisle::app_mealprep.aisle, v.status::app_mealprep.pantry_status");
w("from app_mealprep.households h");
w("cross join (values");
w(
  fx.sampleIngredients
    .map((i) => `  (${q(i.name)}, ${q(i.defaultAisle)}, ${q(i.pantryStatus)})`)
    .join(",\n"),
);
w(") as v(name, aisle, status)");
w("on conflict (household_id, name) do nothing;");
w();

w("-- Recipes.");
w("insert into app_mealprep.recipes (household_id, type, name, method, rating, source_kind, source_ref)");
w(
  "select h.id, v.type::app_mealprep.meal_type, v.name, v.method::app_mealprep.method, " +
    "v.rating::app_mealprep.rating, 'seed'::app_mealprep.source_kind, v.source_ref",
);
w("from app_mealprep.households h");
w("cross join (values");
w(
  fx.sampleRecipes
    .map((r) => `  (${q(r.type)}, ${q(r.name)}, ${q(r.method)}, ${q(r.rating)}, ${q(r.sourceRef)})`)
    .join(",\n"),
);
w(") as v(type, name, method, rating, source_ref)");
w("where not exists (");
w("  select 1 from app_mealprep.recipes r where r.household_id = h.id and r.name = v.name");
w(");");
w();

w("-- One version per recipe, numbered as it was in the prototype so the");
w("-- version badges match.");
w("insert into app_mealprep.recipe_versions");
w("  (household_id, recipe_id, version_no, base_servings, cal, protein_g, carbs_g, fat_g, steps, note, changes)");
w("select r.household_id, r.id, v.version_no, v.base_servings, v.cal, v.protein, v.carbs, v.fat,");
w("       v.steps, v.note, v.changes");
w("from app_mealprep.recipes r");
w("join (values");
w(
  fx.sampleVersions
    .map((v) => {
      const recipe = fx.sampleRecipes.find((r) => r.id === v.recipeId);
      return (
        `  (${q(recipe.name)}, ${v.versionNo}, ${v.baseServings}, ${v.cal}, ${v.protein}, ` +
        `${v.carbs}, ${v.fat}, ${arr(v.steps)}, ${q(v.note)}, ${arr(v.changes)})`
      );
    })
    .join(",\n"),
);
w(") as v(recipe_name, version_no, base_servings, cal, protein, carbs, fat, steps, note, changes)");
w("  on v.recipe_name = r.name");
w("where not exists (");
w("  select 1 from app_mealprep.recipe_versions rv");
w("  where rv.recipe_id = r.id and rv.version_no = v.version_no");
w(");");
w();

w("-- Point each recipe at its current version.");
w("update app_mealprep.recipes r");
w("set current_version_id = rv.id");
w("from app_mealprep.recipe_versions rv");
w("where rv.recipe_id = r.id");
w("  and r.current_version_id is distinct from rv.id");
w("  and rv.version_no = (");
w("    select max(version_no) from app_mealprep.recipe_versions where recipe_id = r.id");
w("  );");
w();

w("-- Ingredients for each version.");
w("insert into app_mealprep.recipe_version_ingredients (version_id, ingredient_id, qty, unit, sort_order)");
w("select rv.id, ing.id, v.qty, v.unit::app_mealprep.unit, v.sort_order");
w("from (values");
const rows = [];
for (const version of fx.sampleVersions) {
  const recipe = fx.sampleRecipes.find((r) => r.id === version.recipeId);
  for (const vi of version.ingredients) {
    const ing = fx.sampleIngredients.find((i) => i.id === vi.ingredientId);
    rows.push(
      `  (${q(recipe.name)}, ${version.versionNo}, ${q(ing.name)}, ${vi.qty}, ${q(vi.unit)}, ${vi.sortOrder})`,
    );
  }
}
w(rows.join(",\n"));
w(") as v(recipe_name, version_no, ingredient_name, qty, unit, sort_order)");
w("join app_mealprep.recipes r on r.name = v.recipe_name");
w("join app_mealprep.recipe_versions rv on rv.recipe_id = r.id and rv.version_no = v.version_no");
w("join app_mealprep.ingredients ing");
w("  on ing.name = v.ingredient_name and ing.household_id = r.household_id");
w("where not exists (");
w("  select 1 from app_mealprep.recipe_version_ingredients x");
w("  where x.version_id = rv.id and x.ingredient_id = ing.id and x.unit = v.unit::app_mealprep.unit");
w(");");
w();
w(
  `-- ${fx.sampleIngredients.length} ingredients, ${fx.sampleRecipes.length} recipes, ${rows.length} version ingredients.`,
);

const out = path.join(root, "supabase", "migrations", "0002_seed.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(
  `wrote ${path.relative(root, out)}: ${fx.sampleIngredients.length} ingredients, ` +
    `${fx.sampleRecipes.length} recipes, ${rows.length} version ingredients`,
);
