-- Starter data: the 12 recipes from the prototype, their
-- ingredients, and the two pantry lists. Generated by scripts/make-seed.mjs;
-- edit the fixture at lib/domain/fixtures/sample.ts and regenerate rather
-- than editing this file. Safe to re-run: it inserts only what is missing.

-- Ingredients, including which pantry list each one is on.
insert into app_mealprep.ingredients (household_id, name, default_aisle, pantry_status)
select h.id, v.name, v.aisle::app_mealprep.aisle, v.status::app_mealprep.pantry_status
from app_mealprep.households h
cross join (values
  ('Eggs', 'Dairy & eggs', 'none'),
  ('Liquid egg whites', 'Dairy & eggs', 'none'),
  ('Baby spinach', 'Produce', 'none'),
  ('Feta', 'Dairy & eggs', 'none'),
  ('Red onion', 'Produce', 'none'),
  ('Olive oil', 'Pantry', 'staple'),
  ('Salt', 'Pantry', 'staple'),
  ('Black pepper', 'Pantry', 'staple'),
  ('Rolled oats', 'Pantry', 'usual'),
  ('Vanilla protein powder', 'Pantry', 'usual'),
  ('Chia seeds', 'Pantry', 'usual'),
  ('2% milk', 'Dairy & eggs', 'none'),
  ('Nonfat Greek yogurt', 'Dairy & eggs', 'none'),
  ('Blueberries', 'Produce', 'none'),
  ('Honey', 'Pantry', 'staple'),
  ('Turkey breakfast sausage', 'Meat & fish', 'none'),
  ('Low-carb tortillas', 'Bakery', 'none'),
  ('Reduced-fat cheddar', 'Dairy & eggs', 'none'),
  ('Bell peppers', 'Produce', 'none'),
  ('Salsa', 'Pantry', 'usual'),
  ('Boneless chicken thighs', 'Meat & fish', 'none'),
  ('Garam masala', 'Pantry', 'staple'),
  ('Garlic', 'Produce', 'usual'),
  ('Lemons', 'Produce', 'none'),
  ('Basmati rice', 'Pantry', 'usual'),
  ('Cucumbers', 'Produce', 'none'),
  ('Cilantro', 'Produce', 'none'),
  ('93% lean ground turkey', 'Meat & fish', 'none'),
  ('Black beans', 'Pantry', 'none'),
  ('Romaine', 'Produce', 'none'),
  ('Limes', 'Produce', 'none'),
  ('Cumin', 'Pantry', 'staple'),
  ('Chili powder', 'Pantry', 'staple'),
  ('Chicken breast', 'Meat & fish', 'none'),
  ('Chickpeas', 'Pantry', 'none'),
  ('Cherry tomatoes', 'Produce', 'none'),
  ('Yellow onions', 'Produce', 'none'),
  ('Fajita seasoning', 'Pantry', 'staple'),
  ('Salmon fillets', 'Meat & fish', 'none'),
  ('Broccoli', 'Produce', 'none'),
  ('Quinoa', 'Pantry', 'usual'),
  ('Flank steak', 'Meat & fish', 'none'),
  ('Low-sodium soy sauce', 'Pantry', 'usual'),
  ('Fresh ginger', 'Produce', 'none'),
  ('Jasmine rice', 'Pantry', 'usual'),
  ('Low-fat cottage cheese', 'Dairy & eggs', 'none'),
  ('Raspberries', 'Produce', 'none'),
  ('Cinnamon', 'Pantry', 'staple'),
  ('Smoked paprika', 'Pantry', 'staple'),
  ('Natural peanut butter', 'Pantry', 'usual'),
  ('Dark chocolate chips', 'Pantry', 'none')
) as v(name, aisle, status)
on conflict (household_id, name) do nothing;

-- Recipes.
insert into app_mealprep.recipes (household_id, type, name, method, rating, source_kind, source_ref)
select h.id, v.type::app_mealprep.meal_type, v.name, v.method::app_mealprep.method, v.rating::app_mealprep.rating, 'seed'::app_mealprep.source_kind, v.source_ref
from app_mealprep.households h
cross join (values
  ('b', 'Egg bite muffins', 'oven', 'keeper', 'example.com/spinach-egg-bites'),
  ('b', 'Protein overnight oats', 'nocook', 'good', 'example.com/overnight-oats'),
  ('b', 'Turkey sausage breakfast burritos', 'stove', 'good', 'example.com/freezer-burritos'),
  ('l', 'Chicken tikka rice bowls', 'oven', 'keeper', 'example.com/chicken-tikka-bowls'),
  ('l', 'Turkey taco bowls', 'stove', 'good', 'example.com/taco-bowls'),
  ('l', 'Greek chicken chickpea salad', 'oven', 'keeper', 'example.com/greek-chickpea-salad'),
  ('d', 'Sheet-pan chicken fajitas', 'oven', 'keeper', 'example.com/sheet-pan-fajitas'),
  ('d', 'Lemon garlic salmon and broccoli', 'oven', 'good', 'example.com/lemon-salmon'),
  ('d', 'Beef and broccoli stir-fry', 'stove', 'work', 'example.com/beef-broccoli'),
  ('s', 'Cottage cheese berry cups', 'nocook', 'keeper', 'Your own recipe'),
  ('s', 'Crispy roasted chickpeas', 'oven', 'good', 'example.com/roasted-chickpeas'),
  ('s', 'Peanut butter protein bites', 'nocook', 'keeper', 'example.com/protein-bites')
) as v(type, name, method, rating, source_ref)
where not exists (
  select 1 from app_mealprep.recipes r where r.household_id = h.id and r.name = v.name
);

-- One version per recipe, numbered as it was in the prototype so the
-- version badges match.
insert into app_mealprep.recipe_versions
  (household_id, recipe_id, version_no, base_servings, cal, protein_g, carbs_g, fat_g, steps, note, changes)
select r.household_id, r.id, v.version_no, v.base_servings, v.cal, v.protein, v.carbs, v.fat,
       v.steps, v.note, v.changes
from app_mealprep.recipes r
join (values
  ('Egg bite muffins', 2, 4, 220, 24, 6, 11, array['Heat the oven to 350°F and oil a 12-cup muffin tin.', 'Sauté the spinach and onion for 3 minutes, then divide into the cups.', 'Whisk the eggs, egg whites, salt and pepper, and pour over.', 'Top with feta and bake 22 to 25 minutes.', 'Cool completely, then pack 3 per container.'], 'Swapped 4 eggs for egg whites and cheddar for feta. Lighter, same protein.', '{}'::text[]),
  ('Protein overnight oats', 2, 4, 370, 31, 44, 8, array['Stir the oats, protein powder and chia together.', 'Whisk in the milk and yogurt until smooth.', 'Divide into jars and top with blueberries and a drizzle of honey.', 'Refrigerate overnight. Keeps 4 days.'], 'Added protein powder and halved the honey.', '{}'::text[]),
  ('Turkey sausage breakfast burritos', 1, 4, 395, 34, 24, 18, array['Brown the sausage with the diced pepper, then set aside.', 'Soft-scramble the eggs in the same pan.', 'Fill the tortillas with egg, sausage, cheddar and salsa, and roll tight.', 'Wrap in foil. Reheat 90 seconds from the fridge or 3 minutes from frozen.'], 'Original recipe.', '{}'::text[]),
  ('Chicken tikka rice bowls', 3, 4, 470, 42, 52, 10, array['Marinate the chicken in yogurt, garam masala, garlic, lemon juice and salt for at least 30 minutes.', 'Roast at 425°F on a sheet pan for 22 to 25 minutes. Rest, then slice.', 'Cook the rice.', 'Toss the cucumber and onion with lemon and cilantro.', 'Pack rice, chicken and salad in separate sections.'], 'Less rice per bowl and double the garlic.', array['Basmati rice 2 cups to 1½ cups', 'Garlic 3 cloves to 6 cloves']),
  ('Turkey taco bowls', 2, 4, 395, 39, 28, 14, array['Brown the turkey with cumin, chili powder and salt.', 'Rinse and warm the beans.', 'Chop the romaine and pack it separately so it stays crisp.', 'Top with turkey, beans, salsa, cheddar and a lime wedge.'], 'Turkey instead of beef. Romaine base, no rice.', '{}'::text[]),
  ('Greek chicken chickpea salad', 2, 4, 450, 40, 36, 16, array['Season the chicken and roast at 425°F for 20 minutes. Rest, then dice.', 'Rinse the chickpeas. Halve the tomatoes and chop the cucumber.', 'Whisk lemon juice and olive oil for the dressing.', 'Pack the salad and chicken together, dressing on the side.'], 'Dressing on the side so it is not soggy by Thursday.', '{}'::text[]),
  ('Sheet-pan chicken fajitas', 2, 4, 390, 41, 30, 12, array['Slice the chicken, peppers and onions into strips.', 'Toss with oil and fajita seasoning and spread over two sheet pans.', 'Roast at 425°F for 20 minutes, stirring once.', 'Squeeze lime over the top. Pack tortillas and yogurt separately.'], 'Greek yogurt instead of sour cream, and two extra peppers.', '{}'::text[]),
  ('Lemon garlic salmon and broccoli', 1, 4, 460, 38, 32, 20, array['Cook the quinoa.', 'Toss the broccoli with oil and salt and roast at 425°F for 10 minutes.', 'Add the salmon with garlic and lemon slices and roast 12 more minutes.', 'Pack with quinoa.'], 'Original recipe.', '{}'::text[]),
  ('Beef and broccoli stir-fry', 1, 4, 460, 36, 48, 14, array['Slice the steak thin against the grain.', 'Sear in batches over high heat and set aside.', 'Stir-fry the broccoli with ginger and garlic, then add soy and honey.', 'Return the beef, toss, and pack over rice.'], 'Original recipe. Beef went tough on reheating, so slice thinner next time.', '{}'::text[]),
  ('Cottage cheese berry cups', 2, 4, 160, 20, 14, 3, array['Divide the cottage cheese into small containers.', 'Top with berries, a little honey and cinnamon.', 'Keep the berries on top so they stay firm. Eat within 4 days.'], 'Raspberries instead of strawberries. They hold up better in the fridge.', '{}'::text[]),
  ('Crispy roasted chickpeas', 1, 4, 180, 8, 24, 6, array['Rinse the chickpeas and dry them very well.', 'Toss with oil, paprika and salt.', 'Roast at 425°F for 30 to 35 minutes, shaking the pan twice.', 'Cool completely before packing or they go soft.'], 'Original recipe.', '{}'::text[]),
  ('Peanut butter protein bites', 2, 4, 190, 12, 18, 8, array['Stir everything together until it holds when pressed.', 'Roll into 12 bites.', 'Chill 30 minutes, then pack 3 per container.'], 'Swapped half the honey for protein powder.', '{}'::text[])
) as v(recipe_name, version_no, base_servings, cal, protein, carbs, fat, steps, note, changes)
  on v.recipe_name = r.name
where not exists (
  select 1 from app_mealprep.recipe_versions rv
  where rv.recipe_id = r.id and rv.version_no = v.version_no
);

-- Point each recipe at its current version.
update app_mealprep.recipes r
set current_version_id = rv.id
from app_mealprep.recipe_versions rv
where rv.recipe_id = r.id
  and r.current_version_id is distinct from rv.id
  and rv.version_no = (
    select max(version_no) from app_mealprep.recipe_versions where recipe_id = r.id
  );

-- Ingredients for each version.
insert into app_mealprep.recipe_version_ingredients (version_id, ingredient_id, qty, unit, sort_order)
select rv.id, ing.id, v.qty, v.unit::app_mealprep.unit, v.sort_order
from (values
  ('Egg bite muffins', 2, 'Eggs', 6, 'count', 0),
  ('Egg bite muffins', 2, 'Liquid egg whites', 2, 'cup', 1),
  ('Egg bite muffins', 2, 'Baby spinach', 5, 'oz', 2),
  ('Egg bite muffins', 2, 'Feta', 3, 'oz', 3),
  ('Egg bite muffins', 2, 'Red onion', 1, 'count', 4),
  ('Egg bite muffins', 2, 'Olive oil', 1, 'tbsp', 5),
  ('Egg bite muffins', 2, 'Salt', 0.5, 'tsp', 6),
  ('Egg bite muffins', 2, 'Black pepper', 0.5, 'tsp', 7),
  ('Protein overnight oats', 2, 'Rolled oats', 2, 'cup', 0),
  ('Protein overnight oats', 2, 'Vanilla protein powder', 4, 'scoop', 1),
  ('Protein overnight oats', 2, 'Chia seeds', 3, 'tbsp', 2),
  ('Protein overnight oats', 2, '2% milk', 2, 'cup', 3),
  ('Protein overnight oats', 2, 'Nonfat Greek yogurt', 1.5, 'cup', 4),
  ('Protein overnight oats', 2, 'Blueberries', 12, 'oz', 5),
  ('Protein overnight oats', 2, 'Honey', 2, 'tbsp', 6),
  ('Turkey sausage breakfast burritos', 1, 'Turkey breakfast sausage', 1, 'lb', 0),
  ('Turkey sausage breakfast burritos', 1, 'Eggs', 8, 'count', 1),
  ('Turkey sausage breakfast burritos', 1, 'Low-carb tortillas', 4, 'count', 2),
  ('Turkey sausage breakfast burritos', 1, 'Reduced-fat cheddar', 3, 'oz', 3),
  ('Turkey sausage breakfast burritos', 1, 'Bell peppers', 1, 'count', 4),
  ('Turkey sausage breakfast burritos', 1, 'Salsa', 0.5, 'cup', 5),
  ('Chicken tikka rice bowls', 3, 'Boneless chicken thighs', 2, 'lb', 0),
  ('Chicken tikka rice bowls', 3, 'Nonfat Greek yogurt', 1, 'cup', 1),
  ('Chicken tikka rice bowls', 3, 'Garam masala', 2, 'tbsp', 2),
  ('Chicken tikka rice bowls', 3, 'Garlic', 6, 'clove', 3),
  ('Chicken tikka rice bowls', 3, 'Lemons', 2, 'count', 4),
  ('Chicken tikka rice bowls', 3, 'Basmati rice', 1.5, 'cup', 5),
  ('Chicken tikka rice bowls', 3, 'Cucumbers', 1, 'count', 6),
  ('Chicken tikka rice bowls', 3, 'Red onion', 1, 'count', 7),
  ('Chicken tikka rice bowls', 3, 'Cilantro', 1, 'bunch', 8),
  ('Turkey taco bowls', 2, '93% lean ground turkey', 2, 'lb', 0),
  ('Turkey taco bowls', 2, 'Black beans', 2, 'can', 1),
  ('Turkey taco bowls', 2, 'Romaine', 1, 'head', 2),
  ('Turkey taco bowls', 2, 'Salsa', 1, 'cup', 3),
  ('Turkey taco bowls', 2, 'Reduced-fat cheddar', 3, 'oz', 4),
  ('Turkey taco bowls', 2, 'Limes', 2, 'count', 5),
  ('Turkey taco bowls', 2, 'Cumin', 1, 'tbsp', 6),
  ('Turkey taco bowls', 2, 'Chili powder', 1, 'tbsp', 7),
  ('Greek chicken chickpea salad', 2, 'Chicken breast', 1.5, 'lb', 0),
  ('Greek chicken chickpea salad', 2, 'Chickpeas', 2, 'can', 1),
  ('Greek chicken chickpea salad', 2, 'Cucumbers', 2, 'count', 2),
  ('Greek chicken chickpea salad', 2, 'Cherry tomatoes', 1, 'pint', 3),
  ('Greek chicken chickpea salad', 2, 'Feta', 4, 'oz', 4),
  ('Greek chicken chickpea salad', 2, 'Lemons', 1, 'count', 5),
  ('Greek chicken chickpea salad', 2, 'Olive oil', 3, 'tbsp', 6),
  ('Sheet-pan chicken fajitas', 2, 'Chicken breast', 2, 'lb', 0),
  ('Sheet-pan chicken fajitas', 2, 'Bell peppers', 4, 'count', 1),
  ('Sheet-pan chicken fajitas', 2, 'Yellow onions', 2, 'count', 2),
  ('Sheet-pan chicken fajitas', 2, 'Limes', 2, 'count', 3),
  ('Sheet-pan chicken fajitas', 2, 'Low-carb tortillas', 8, 'count', 4),
  ('Sheet-pan chicken fajitas', 2, 'Nonfat Greek yogurt', 0.5, 'cup', 5),
  ('Sheet-pan chicken fajitas', 2, 'Fajita seasoning', 2, 'tbsp', 6),
  ('Sheet-pan chicken fajitas', 2, 'Olive oil', 2, 'tbsp', 7),
  ('Lemon garlic salmon and broccoli', 1, 'Salmon fillets', 1.5, 'lb', 0),
  ('Lemon garlic salmon and broccoli', 1, 'Broccoli', 2, 'lb', 1),
  ('Lemon garlic salmon and broccoli', 1, 'Lemons', 2, 'count', 2),
  ('Lemon garlic salmon and broccoli', 1, 'Garlic', 4, 'clove', 3),
  ('Lemon garlic salmon and broccoli', 1, 'Quinoa', 1, 'cup', 4),
  ('Lemon garlic salmon and broccoli', 1, 'Olive oil', 2, 'tbsp', 5),
  ('Beef and broccoli stir-fry', 1, 'Flank steak', 1.5, 'lb', 0),
  ('Beef and broccoli stir-fry', 1, 'Broccoli', 1.5, 'lb', 1),
  ('Beef and broccoli stir-fry', 1, 'Low-sodium soy sauce', 0.25, 'cup', 2),
  ('Beef and broccoli stir-fry', 1, 'Fresh ginger', 1, 'count', 3),
  ('Beef and broccoli stir-fry', 1, 'Garlic', 3, 'clove', 4),
  ('Beef and broccoli stir-fry', 1, 'Jasmine rice', 1.5, 'cup', 5),
  ('Beef and broccoli stir-fry', 1, 'Honey', 1, 'tbsp', 6),
  ('Cottage cheese berry cups', 2, 'Low-fat cottage cheese', 3, 'cup', 0),
  ('Cottage cheese berry cups', 2, 'Raspberries', 6, 'oz', 1),
  ('Cottage cheese berry cups', 2, 'Honey', 1, 'tbsp', 2),
  ('Cottage cheese berry cups', 2, 'Cinnamon', 0.5, 'tsp', 3),
  ('Crispy roasted chickpeas', 1, 'Chickpeas', 2, 'can', 0),
  ('Crispy roasted chickpeas', 1, 'Olive oil', 1, 'tbsp', 1),
  ('Crispy roasted chickpeas', 1, 'Smoked paprika', 1, 'tsp', 2),
  ('Crispy roasted chickpeas', 1, 'Salt', 0.5, 'tsp', 3),
  ('Peanut butter protein bites', 2, 'Rolled oats', 1, 'cup', 0),
  ('Peanut butter protein bites', 2, 'Vanilla protein powder', 2, 'scoop', 1),
  ('Peanut butter protein bites', 2, 'Natural peanut butter', 0.5, 'cup', 2),
  ('Peanut butter protein bites', 2, 'Honey', 2, 'tbsp', 3),
  ('Peanut butter protein bites', 2, 'Dark chocolate chips', 2, 'tbsp', 4)
) as v(recipe_name, version_no, ingredient_name, qty, unit, sort_order)
join app_mealprep.recipes r on r.name = v.recipe_name
join app_mealprep.recipe_versions rv on rv.recipe_id = r.id and rv.version_no = v.version_no
join app_mealprep.ingredients ing
  on ing.name = v.ingredient_name and ing.household_id = r.household_id
where not exists (
  select 1 from app_mealprep.recipe_version_ingredients x
  where x.version_id = rv.id and x.ingredient_id = ing.id and x.unit = v.unit::app_mealprep.unit
);

-- 51 ingredients, 12 recipes, 79 version ingredients.
